### ISSUE TITLE
Installation process

### ISSUE THREAD

**Issue by CorentinvdBdO** [j-rausch/DSG#1]
Half the repos in the installation process are not found, pytorch 1.11 is no longer served by pip, neither is the numpy version. 

Is there a simpler installation process to your knowledge? I would really like to try your code but the wall of installs is preventing me from going forward.

**Comment by j-rausch** [comment]
We only tested the implementation with the packages that are currently specified. If you'd like, you could try to run it with newer versions of some packages. I'd be happy to know if it works for you.

For the current package versions, maybe these sources are helpful to you:
https://stackoverflow.com/questions/51912284/how-to-downgrade-numpy
https://pytorch.org/get-started/previous-versions/#v1110
