### ISSUE TITLE
OCR

### ISSUE THREAD

**Issue by Alex-Citeroni** [j-rausch/DSG#2]
Hi, how can I get the text of a image through OCR? Is there already something implemented, or do I need to do it outside of this project?

**Comment by j-rausch** [comment]
Hi Alex, we used OCR extractions that were internally available at E-Periodica and obtained with off-the-shelf OCR tools. We are currently looking into whether it is possible to also share the texts. In the meantime, you should be able to retrieve very similar texts with Tesseract or other OCR tools with comparable performance.

**Comment by j-rausch** [comment]
I've double checked and the txt files we ran our demo on were created with ABBYY. If you're not using ABBYY, you might need to adapt the OCR outputs to match the ABBYY format or refactor the hocr creation code slightly.
