### ISSUE TITLE
figure graphic 

### ISSUE THREAD

**Issue by Alex-Citeroni** [j-rausch/DSG#4]
Is there any setting that can be added during the execution of demo.py to include the div for the graphic figures contained within the image in the hOCR, or is it automatic? Because I'm testing it on various images, and currently, it's not being detected. However, I noticed that it's present in sysdemo.

**Comment by j-rausch** [comment]
Hey, have you checked whether any figure graphic objects are actually detected in the entity detection stage for your own data samples? If no such entities are detected, they would also not appear in the hOCR files afterwards.

**Comment by Alex-Citeroni** [comment]
Yes, I have noticed that bounding boxes are constructed on the document, and some of them are referred to as 'figure graphics,' but when I checked the hOCR file, I couldn't find any trace of them.

**Comment by j-rausch** [comment]
I see, thanks for the info. Could you perhaps share the generated files connected to your issue?

**Comment by Alex-Citeroni** [comment]
[Example DSG.zip](https://github.com/j-rausch/DSG/files/13316913/Example.DSG.zip)
Hi, these are two examples that I tested, the first (page 1) managed to recognize the figure graphic and also managed to write it into the hocr file. The second (page 115) instead recognized the figure graphic, but was unable to write it into the hocr file and there are many others like this example.

**Comment by gusevm1** [comment]
Hey a new branch called feature/postproc has been created and can now be used that resolves your issue. Thank you for pointing out the problem there was a intrinsic issue in the postprocessing.
