### ISSUE TITLE
TXT files in sysdemo

### ISSUE THREAD

**Issue by boostpaal** [j-rausch/DSG#5]
Hi, and thank you for this great project.

I am trying to test on my own image, and I don't know how to generate the accompanied .txt file for the image.
I see there is one in the sysdemo folder.
How do I generate this file?
Thank you.

**Comment by j-rausch** [comment]
Hey, thanks using this project! This is connected to #2 - we're currently looking into whether there is a way for us to share these files. You should be able to generate similar text files yourself with OCR tools such as ABBYY, Tesseract, etc.

**Comment by j-rausch** [comment]
At the moment, we unfortunately cannot share the OCR outputs, due to copyright restrictions. I'd recommend using an OCR tool to recreate them.
