### ISSUE TITLE
Some questions about TXT files

### ISSUE THREAD

**Issue by WuHenry-0609** [j-rausch/DSG#6]
Hi, thank you for this great project!
I'm trying to test my own images and I got OCR file using Tesseract, but the format is different from the OCR file in sysdemo.
What do the two numbers at the beginning of the OCR file in sysdemo mean? And are the four numbers following each word the coordinates?
I look forward to your reply.

**Comment by j-rausch** [comment]
Hey, I've double-checked and the txt files that we've previously worked on were created with ABBYY and not Tesseract. For the time being, converting the Tesseract outputs to match the ABBYY txt format could be a quick workaround. The two numbers at the beginning describe the page dimensions. The four numbers following each word are the specify the bounding box that describes the word.

**Comment by WuHenry-0609** [comment]
Hi! Thank you for your reply! 
In addition, I found another problem:

I changed the "chr-001_1974_013_0199.jpg" image in sysdemo to png format, and ran the following instructions according to the "Demonstration of our system" section in the README.md:
`python visualizations/demo.py --config-file ./configs/sgg_end2end_EP.yaml --input ./sysdemo/chr-001_1974_013_0199.png --output ./sysdemo --raw_output ./sysdemo --opts MODEL.ROI_SCENEGRAPH_HEAD.PREDICT_USE_VISION True MODEL.WEIGHTS ./checkpoints/DSG_E2E_eperiodica/dsg_e2e_eperiodica_checkpoint.pth TEST.USE_GRAMMAR_POSTPROCESSING True` 

Then I got a pt format file and two png format pictures. Finally I ran system_demonstration.ipynb and got the hocr file.

But I found that the hocr file obtained by following the above operation is different from the hocr file obtained by directly running system_demonstration.ipynb:
This is the hocr file I got from the above operation:
![image](https://github.com/j-rausch/DSG/assets/150360784/5df002d4-f21b-4a62-a7d6-7a8fec43946f)

This is the hocr file obtained by running system_demonstration.ipynb directly:
![image](https://github.com/j-rausch/DSG/assets/150360784/54a45c7d-de42-43ab-8526-3fd54f534b6a)

I think the reason for this may be that the pt file obtained by running demo.py is different from the original pt file in sysdemo. Could you resolve this problem?
I look forward to hearing from you.

**Comment by gusevm1** [comment]
I'll look into that, and I believe this issue will be resolved, since as you said the .pt files from the different demos could be different, thank you for pointing it out!

**Comment by gusevm1** [comment]
Thank you for pointing it out, we now have a new branch called feature/postproc. Check it out there and rerun what you tried before the issue should be resolved by now.
