### ISSUE TITLE
Finetuning/Training our Own Custom Dataset.

### ISSUE THREAD

**Issue by purnasai** [j-rausch/DSG#7]
Hi, Thank you for the great work. 

I see that the repo only has Prediction/demo codes available. Can you please add Finetuning code and Custom Dataset format that the model accepts. Can you also please add all details required to custom train on the datasets.

Thank you

**Comment by j-rausch** [comment]
Hi, thanks for your interest in this project! You'd need to go through several preprocessing steps for the dataset. This process relies on workflows defined in preceding open source works.

Update your config to point to the new dataset files, here are the lines used for E-Periodica, for reference:
https://github.com/j-rausch/DSG/blob/main/segmentationsg/data/tools/config.py#L149

Creating the dataset files follows the instructions provided in a range of previous open source repos for scene graph generation. See here for reference:
https://github.com/KaihuaTang/Scene-Graph-Benchmark.pytorch/blob/master/DATASET.md
We tried to re-structure this data preparation in our workflow. For reference, see https://github.com/j-rausch/DSG/blob/main/data/data_preprocessing/helper_preprocessing.py#L132 

Then, register your dataset, e.g. by adapting this file with your new custom dataset.
https://github.com/j-rausch/DSG/blob/main/segmentationsg/data/tools/utils.py#L87

For fine-tuning, you'd likely want to specify a pretrained DSG model, e.g. E-Periodica checkpoint, and specify it via command line or in a config file like here:
https://github.com/j-rausch/DSG/blob/main/configs/sgg_end2end_EP.yaml#L6
