### ISSUE TITLE
Evaluation on eperiodica and arxivdoc

### ISSUE THREAD

**Issue by JarvisUSTC** [j-rausch/DSG#8]
Hi, Johannes, thanks for your great project! I want to follow your datasets and work to do research. However, I haven't found the evaluation scripts to reproduce the results in DSG paper.
I tried to modify the training scripts like:
`CUDA_VISIBLE_DEVICES=0 python scripts/train_doc_SG_head.py \
  --config-file ./configs/sgg_end2end_EP.yaml \
  --num-gpus 1  \
  --eval-only \
  --resume \
  MODEL.ROI_SCENEGRAPH_HEAD.PREDICT_USE_VISION  True \
  OUTPUT_DIR ./output/eval \
  MODEL.WEIGHTS ./checkpoints/DSG_E2E_eperiodica/dsg_e2e_eperiodica_checkpoint.pth`
However, it reported a bug:
`TypeError: _evaluate_predictions_on_coco() got an unexpected keyword argument 'use_fast_impl'`
I do not know what is the correct command.

Thanks! Look forward to your reply!

**Comment by j-rausch** [comment]
Hey, thanks for your interest in our project! I believe this is due to changes to the evaluation code in detectron2. The keyword argument was removed in this commit: https://github.com/facebookresearch/detectron2/commit/de3869eb18691096186d5aa9b716573c5f374bc6
Using a previous commit should resolve this (e.g. `45b3fce`).

**Comment by j-rausch** [comment]
You can execute evaluation with a command like this:
```
CUDA_VISIBLE_DEVICES=1 python scripts/train_doc_SG_head.py \
  --config-file ./configs/sgg_end2end_EP.yaml \
  --num-gpus 1 \
  --eval-only \
  SOLVER.IMS_PER_BATCH 1 \
  MODEL.ROI_HEADS.SCORE_THRESH_TEST 0.1 \
  MODEL.ROI_SCENEGRAPH_HEAD.PREDICT_USE_VISION  True \
  MODEL.WEIGHTS ./checkpoints/DSG_E2E_eperiodica/dsg_e2e_eperiodica_checkpoint.pth \
  OUTPUT_DIR ./data/eval/DSG_E2E_eperiodica \
 ```
Note that we shared two fine-tuned model checkpoints in this repository that allow further application of DSG, but don't exactly correspond to all the evaluated models in the paper.
